default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: eatracker_development

test:
  <<: *default
  database: eatracker_test

production:
  <<: *default
  database: eatracker_production
